apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-java-app
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: fake-java-app
          resources:
            requests: { cpu: "100m", memory: "256Mi" }
            limits:   { cpu: "250m", memory: "512Mi" }
          envFrom:
            - configMapRef:
                name: fake-java-app-config
